# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
  form_themes:
    - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
  configs:
    default:
      versionCheck: false #pour éviter un message d'erreur de version soit disant non sécure(ck éditor veut faire de l'argent : 9600 $ /an la licence !) lors de l'affichage de ckeditor
      language: fr
      toolbar: full
      filebrowserBrowseRoute: elfinder
      filebrowserBrowseRouteParameters: [ ]
      config.extraPlugins: 'wordcount,notification,autogrow'
      width: 900px

    main_config:
      language: fr
      toolbar: full


