# see https://symfony.com/doc/current/reference/configuration/framework.html
parameters:
  env(HTTP_METHOD_OVERRIDE): 'true'
framework:
  annotations:
    enabled: false
  http_method_override: '%env(bool:HTTP_METHOD_OVERRIDE)%'
  secret: '%env(APP_SECRET)%'
  handle_all_throwables: true
  #csrf_protection: ~
  #http_method_override: true
  #http_cache: true
  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    cookie_lifetime: 43200
    gc_maxlifetime: 43200
    enabled: true
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native
  #esi: true
  #fragments: true
  php_errors:
    log: true